import json
import stat
import subprocess
import sys
import tempfile
import textwrap
import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT = REPO_ROOT / "scripts" / "complexity_calibrate.py"


class ComplexityCalibrateTests(unittest.TestCase):
    def make_fake_vowc(self, tmp: Path) -> Path:
        fake = tmp / "fake-vowc"
        payload = {
            "files": [
                {
                    "functions": [
                        {
                            "name": "tiny",
                            "line": 1,
                            "complexity_score": 10,
                            "size": {"nloc": 5},
                            "structural": {"cognitive": 0, "cyclomatic": 1},
                        }
                    ]
                }
            ]
        }
        fake.write_text(
            textwrap.dedent(
                f"""\
                #!{sys.executable}
                import json

                print(json.dumps({json.dumps(payload)}))
                """
            ),
            encoding="utf-8",
        )
        fake.chmod(fake.stat().st_mode | stat.S_IXUSR)
        return fake

    def make_source_dir(self, tmp: Path) -> Path:
        src = tmp / "src"
        src.mkdir()
        (src / "sample.vow").write_text("fn tiny() -> i64 { return 1; }\n", encoding="utf-8")
        return src

    def run_calibrate(self, tmp: Path, *args: str) -> subprocess.CompletedProcess:
        fake_vowc = self.make_fake_vowc(tmp)
        src = self.make_source_dir(tmp)
        return subprocess.run(
            [
                sys.executable,
                str(SCRIPT),
                "--vowc",
                str(fake_vowc),
                "--dir",
                str(src),
                *args,
            ],
            cwd=tmp,
            capture_output=True,
            text=True,
        )

    def test_default_output_goes_to_reports_out(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            tmp = Path(tmpdir)

            res = self.run_calibrate(tmp)

            self.assertEqual(res.returncode, 0, res.stderr)
            report = tmp / "reports.out" / "complexity-calibration.md"
            self.assertTrue(report.exists())
            self.assertFalse((tmp / "reports" / "complexity-calibration.md").exists())
            text = report.read_text(encoding="utf-8")
            self.assertIn("_Generated by scripts/complexity_calibrate.py over", text)

    def test_reports_output_requires_date_and_dated_filename(self):
        cases = [
            ("missing date", ["--out", "reports/complexity-calibration.md"]),
            (
                "undated filename",
                ["--date", "2026-06-18", "--out", "reports/complexity-calibration.md"],
            ),
        ]
        for name, args in cases:
            with self.subTest(name=name), tempfile.TemporaryDirectory() as tmpdir:
                tmp = Path(tmpdir)

                res = self.run_calibrate(tmp, *args)

                self.assertNotEqual(res.returncode, 0)
                self.assertIn("error:", res.stderr)

    def test_reports_output_with_date_includes_retention_metadata(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            tmp = Path(tmpdir)

            res = self.run_calibrate(
                tmp,
                "--date",
                "2026-06-18",
                "--out",
                "reports/2026-06-18-complexity-calibration.md",
                "--retention-class",
                "current-baseline",
            )

            self.assertEqual(res.returncode, 0, res.stderr)
            report = tmp / "reports" / "2026-06-18-complexity-calibration.md"
            text = report.read_text(encoding="utf-8")
            self.assertIn(
                "_Generated 2026-06-18 by scripts/complexity_calibrate.py over",
                text,
            )
            self.assertIn(
                "_Retention: `current-baseline` for the `complexity-calibration` stream.",
                text,
            )


if __name__ == "__main__":
    unittest.main()
