#!/usr/bin/env python3
"""Grammar-directed corpus generator for the differential runner (#905).

Emits random well-formed-per-grammar Vow programs so the differential sweep sees
constructs no hand-written fixture happens to use. This is the generator half
only: the programs it writes are consumed by scripts/equivalence.py, which
already implements the observables #905 asks for (accept/reject parity,
error_code parity, runtime parity, and the fail-closed no-panic/no-SIGSEGV
invariant).

Sequenced last on purpose. Google's giflib pilot ran a differential fuzzer for
200M iterations over six days and found nothing, while corpus replay and
adversarial review found the two real bugs; this repo's own first corpus sweep
found a total miscompile of gcd (#1087) in minutes. Generation is the
lowest-yield tier, so it runs on leftover budget rather than ahead of the others.

Determinism is a hard requirement: a divergence nobody can reproduce is not
actionable. The seed is an explicit argument, never a clock read.
"""

import argparse
import hashlib
import random
import sys
from pathlib import Path

# Weighted toward the surface where this repo's compilers have actually
# diverged: integer width and signedness, checked vs wrapping arithmetic, match
# and pattern handling, and loop-carried mutation (the #1087 family).
INT_TYPES = ["i8", "i16", "i32", "i64", "u8", "u16", "u32", "u64"]
ARITH = ["+", "-", "*"]
CHECKED = ["+!", "-!", "*!"]
CMP = ["<", "<=", ">", ">=", "==", "!="]


def lit(rng, ty):
    """A literal inside `ty`'s range.

    Boundary values are over-sampled: width-related divergences cluster at the
    edges, not in the middle.
    """
    signed = ty.startswith("i")
    bits = int(ty[1:])
    if signed:
        lo, hi = -(2 ** (bits - 1)), 2 ** (bits - 1) - 1
    else:
        lo, hi = 0, 2**bits - 1
    edges = [lo, lo + 1, 0, 1, hi - 1, hi]
    if rng.random() < 0.5:
        return str(rng.choice(edges))
    return str(rng.randint(lo, hi))


def gen_arith_fn(rng, name, ty):
    op = rng.choice(CHECKED if rng.random() < 0.4 else ARITH)
    return (
        f"fn {name}(a: {ty}, b: {ty}) -> {ty} {{\n"
        f"  a {op} b\n"
        f"}}\n"
    )


def gen_loop_carry_fn(rng, name, ty):
    """A loop-body `let` reading a loop-carried mutable variable.

    This is the #1087 shape. Generating variants of a known-divergent pattern is
    the cheapest way to find its siblings.
    """
    body = [
        f"fn {name}(n: {ty}) -> {ty} {{",
        f"  let mut acc: {ty} = {lit(rng, ty)};",
        f"  let mut i: {ty} = n;",
        "  while i > 0 {",
    ]
    if rng.random() < 0.6:
        body += [
            f"    let tmp: {ty} = acc;",
            f"    acc = i;",
            f"    i = tmp;" if rng.random() < 0.5 else "    i = i - 1;",
        ]
    else:
        body += [
            f"    acc = acc {rng.choice(ARITH)} i;",
            "    i = i - 1;",
        ]
    body += ["  }", "  acc", "}", ""]
    return "\n".join(body)


def gen_match_fn(rng, name, ty):
    arms = rng.randint(2, 4)
    lines = [
        f"enum E{name} {{",
        *[f"  V{i}," for i in range(arms)],
        "}",
        "",
        f"fn {name}(e: E{name}) -> {ty} {{",
        "  match e {",
    ]
    for i in range(arms):
        lines.append(f"    E{name}::V{i} => {lit(rng, ty)},")
    lines += ["  }", "}", ""]
    return "\n".join(lines)


def gen_cmp_fn(rng, name, ty):
    return (
        f"fn {name}(a: {ty}, b: {ty}) -> bool {{\n"
        f"  a {rng.choice(CMP)} b\n"
        f"}}\n"
    )


def gen_contract_fn(rng, name, ty):
    """A contracted function, so the generated corpus reaches the verifier too."""
    return (
        f"fn {name}(a: {ty}) -> {ty} vow {{\n"
        f"  requires: a > 0,\n"
        f"  ensures: result >= 0\n"
        f"}} {{\n"
        f"  a\n"
        f"}}\n"
    )


GENERATORS = [gen_arith_fn, gen_loop_carry_fn, gen_match_fn, gen_cmp_fn,
              gen_contract_fn]


def gen_program(rng, index):
    ty = rng.choice(INT_TYPES)
    n = rng.randint(1, 3)
    parts, names = [], []
    for k in range(n):
        name = f"f{k}"
        names.append(name)
        parts.append(rng.choice(GENERATORS)(rng, name, ty))

    # `main` must print something: a program with no output makes the runtime
    # stdout observable vacuous, and a vacuous check is worse than none because
    # it reads as coverage.
    main = [
        "fn main() -> i32 [io] {",
        f"  print_i64({lit(rng, 'i32')});",
        "  0",
        "}",
        "",
    ]

    return (
        f"// Generated by scripts/gen_corpus.py (#905). Do not edit.\n"
        f"module Gen{index}\n\n" + "\n".join(parts) + "\n" + "\n".join(main)
    )


def main():
    ap = argparse.ArgumentParser(description="Generate a Vow corpus (#905)")
    ap.add_argument("--seed", type=int, required=True,
                    help="RNG seed; required, so every run is reproducible")
    ap.add_argument("--count", type=int, default=100)
    ap.add_argument("--output-dir", default="generated-corpus")
    args = ap.parse_args()

    rng = random.Random(args.seed)
    outdir = Path(args.output_dir)
    outdir.mkdir(parents=True, exist_ok=True)

    written = []
    for i in range(args.count):
        text = gen_program(rng, i)
        # Name by content hash so a regenerated corpus with the same seed
        # produces byte-identical filenames, and a divergence found in
        # gen_<hash>.vow is re-findable from the seed alone.
        digest = hashlib.sha256(text.encode()).hexdigest()[:12]
        p = outdir / f"gen_{i:04d}_{digest}.vow"
        p.write_text(text)
        written.append(p)

    print(f"wrote {len(written)} programs to {outdir} (seed {args.seed})")
    print(f"next: python3 scripts/equivalence.py {outdir} --no-ledger")
    return 0


if __name__ == "__main__":
    sys.exit(main())
